volumes:
  dvwa:


networks:
  dvwa:


services:
  dvwa:
    build: .
    image: ghcr.io/digininja/dvwa:latest
    # Change `always` to `build` to build from local source
    pull_policy: always
    environment:
      - DB_SERVER=${DVWA_DB_SERVER:-db}
      - DB_DATABASE=${DVWA_DB_DATABASE:-dvwa}
      - DB_USER=${DVWA_DB_USER:-dvwa}
      - DB_PASSWORD=${DVWA_DB_PASSWORD}
    depends_on:
      - db
    # Uncomment the next 2 lines to serve local source
    # volumes:
    #   - ./:/var/www/html
    networks:
      - dvwa
    ports:
      - 127.0.0.1:4280:80
    restart: unless-stopped

  db:
    image: docker.io/library/mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DVWA_DB_DATABASE:-dvwa}
      - MYSQL_USER=${DVWA_DB_USER:-dvwa}
      - MYSQL_PASSWORD=${DVWA_DB_PASSWORD}
    volumes:
      - dvwa:/var/lib/mysql
    networks:
      - dvwa
    restart: unless-stopped
