; This file attempts to overwrite the original php.ini file. Doesnt always work.

magic_quotes_gpc = Off
allow_url_fopen = on
; SECURITY: allow_url_include enables remote file inclusion and should be off by default.
allow_url_include = off
